/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface GourmetInterface extends utils.Interface {
  functions: {
    "Evaluate(uint256,uint256)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "Evaluate"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "Evaluate",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(functionFragment: "Evaluate", data: BytesLike): Result;

  events: {
    "starLog(uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "starLog"): EventFragment;
}

export interface starLogEventObject {
  result: BigNumber;
}
export type starLogEvent = TypedEvent<[BigNumber], starLogEventObject>;

export type starLogEventFilter = TypedEventFilter<starLogEvent>;

export interface Gourmet extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: GourmetInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    Evaluate(
      _uStar: PromiseOrValue<BigNumberish>,
      _shopId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  Evaluate(
    _uStar: PromiseOrValue<BigNumberish>,
    _shopId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    Evaluate(
      _uStar: PromiseOrValue<BigNumberish>,
      _shopId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "starLog(uint256)"(result?: null): starLogEventFilter;
    starLog(result?: null): starLogEventFilter;
  };

  estimateGas: {
    Evaluate(
      _uStar: PromiseOrValue<BigNumberish>,
      _shopId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    Evaluate(
      _uStar: PromiseOrValue<BigNumberish>,
      _shopId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
