/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Gourmet } from "./Gourmet";
export * as factories from "./factories";
export { Gourmet__factory } from "./factories/Gourmet__factory";
