/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../common";
import type { Gourmet, GourmetInterface } from "../Gourmet";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "shopId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "result",
        type: "uint256",
      },
    ],
    name: "rateLog",
    type: "event",
  },
  {
    stateMutability: "payable",
    type: "fallback",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_shopId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_uStar",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_userPoint",
        type: "uint256",
      },
    ],
    name: "Rating",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506103bf806100206000396000f3fe6080604052600436106100225760003560e01c8063666b035f1461002b57610029565b3661002957005b005b34801561003757600080fd5b50610052600480360381019061004d91906101bf565b610054565b005b600080826127106100659190610270565b9050600080600087815260200190815260200160002054141561009657600a8461008f91906102a1565b915061012d565b60648114156100dc576002600a856100ae91906102a1565b600080888152602001908152602001600020546100cb91906102fb565b6100d59190610270565b915061012c565b6064816100e991906102fb565b6103e8856100f791906102a1565b826000808981526020019081526020016000205461011591906102a1565b61011f91906102fb565b6101299190610270565b91505b5b81600080878152602001908152602001600020819055507ff25511480bd4962f88c86048335a3eefc13e51d2709031c9a1fd1530359526588583604051610175929190610360565b60405180910390a15050505050565b600080fd5b6000819050919050565b61019c81610189565b81146101a757600080fd5b50565b6000813590506101b981610193565b92915050565b6000806000606084860312156101d8576101d7610184565b5b60006101e6868287016101aa565b93505060206101f7868287016101aa565b9250506040610208868287016101aa565b9150509250925092565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052601260045260246000fd5b7f4e487b7100000000000000000000000000000000000000000000000000000000600052601160045260246000fd5b600061027b82610189565b915061028683610189565b92508261029657610295610212565b5b828204905092915050565b60006102ac82610189565b91506102b783610189565b9250817fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff04831182151516156102f0576102ef610241565b5b828202905092915050565b600061030682610189565b915061031183610189565b9250827fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff0382111561034657610345610241565b5b828201905092915050565b61035a81610189565b82525050565b60006040820190506103756000830185610351565b6103826020830184610351565b939250505056fea26469706673582212205fbeeae8d0a98717d456932a76042d6509b5e69ddf13d821e82c9525882f2e7364736f6c63430008090033";

type GourmetConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: GourmetConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Gourmet__factory extends ContractFactory {
  constructor(...args: GourmetConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<Gourmet> {
    return super.deploy(overrides || {}) as Promise<Gourmet>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): Gourmet {
    return super.attach(address) as Gourmet;
  }
  override connect(signer: Signer): Gourmet__factory {
    return super.connect(signer) as Gourmet__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): GourmetInterface {
    return new utils.Interface(_abi) as GourmetInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Gourmet {
    return new Contract(address, _abi, signerOrProvider) as Gourmet;
  }
}
